name: Deploy to Azure SQL Database

on:
  push:
    branches:
      - master  # Adjust this as necessary

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Adjust this as necessary

    - name: Build DACPAC from SQL project
      run: dotnet build **/*.sqlproj /p:OutputPath=./output
      # This step assumes you're building a DACPAC from a SQL project.
      # If you already have a DACPAC, you can skip this step.

    - name: Deploy DACPAC to Azure SQL Database
      uses: azure/sql-action@v1
      with:
        server-name: your_server_name.database.windows.net  # Update this
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: ./output/AdventureWorks2012.sqlproj.dacpac  # Update the path to your DACPAC
