AdventureWorks2012name: Deploy to Azure SQL Database

on:
  push:
    branches:
      - master  # Adjust this as necessary

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build DACPAC from SQL project
      run: |
         msbuild.exe AdventureWorks2012/AdventureWorks2012.sqlproj /p:Configuration=Release
      # dotnet build **/*.sqlproj /p:OutputPath=./output
      # This step assumes you're building a DACPAC from a SQL project.
      # If you already have a DACPAC, you can skip this step.
      
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: SQLDB
        path: $ {{ github.workspace }}/bin/Release

    - name: Deploy DACPAC to Azure SQL Database
      uses: azure/sql-action@v1
      with:
        server-name: your_server_name.database.windows.net  # Update this
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: ./output/AdventureWorks2012.sqlproj.dacpac  # Update the path to your DACPAC
