
name: Terraform Azure Deployment

on:
  push:
    branches:
      - master
    paths:
    - .github/workflows/tf.yml

jobs:
  terraform:
    runs-on: self-hosted

    # env:
    #   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
